# Generated by Django 6.0.8 on 2026-09-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=20, verbose_name="カテゴリー"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="商品画像")),
                ("Date", models.DateField(verbose_name="登録日")),
                (
                    "categorys",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prepare.category",
                        verbose_name="カテゴリー",
                    ),
                ),
            ],
        ),
    ]
