# Generated by Django 6.0.8 on 2026-09-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mypage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名前")),
                ("breed", models.CharField(max_length=100, verbose_name="犬種")),
                ("birthday", models.DateField(verbose_name="誕生日")),
                ("personality", models.CharField(max_length=200, verbose_name="性格")),
                (
                    "allergy",
                    models.CharField(max_length=200, verbose_name="アレルギー"),
                ),
                (
                    "rabies_vaccine_date",
                    models.DateField(blank=True, verbose_name="狂犬病ワクチン接種日"),
                ),
                (
                    "mixed_vaccine_date",
                    models.DateField(blank=True, verbose_name="混合ワクチン接種日"),
                ),
                (
                    "mixed_vaccine_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("5", "5種"),
                            ("6", "6種"),
                            ("7", "7種"),
                            ("8", "8種"),
                            ("10", "10種"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="混合ワクチン種別",
                    ),
                ),
            ],
        ),
    ]
