# Generated by Django 6.0.8 on 2026-09-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogruns", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mypage",
            new_name="Profile",
        ),
    ]
