# Generated by Django 6.0.8 on 2026-09-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogruns", "0002_rename_mypage_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="プロフィール画像",
            ),
        ),
    ]
