# Generated by Django 6.0.8 on 2026-09-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogruns", "0003_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="mixed_vaccine_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="memo",
            field=models.TextField(blank=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mixed_vaccine_date",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="混合ワクチン接種済み証",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rabies_vaccine_date",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="狂犬病ワクチン接種済み証",
            ),
        ),
    ]
