# Generated by Django 6.0.8 on 2026-09-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogruns", "0004_remove_profile_mixed_vaccine_type_profile_memo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DogRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("west", "西部"),
                            ("central", "中部"),
                            ("east", "東部"),
                            ("izu", "伊豆"),
                        ],
                        max_length=20,
                        verbose_name="エリア",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="施設名")),
                ("parking", models.BooleanField(default=False, verbose_name="駐車場")),
                ("water", models.BooleanField(default=False, verbose_name="水道")),
                ("restroom", models.BooleanField(default=False, verbose_name="トイレ")),
                ("shower", models.BooleanField(default=False, verbose_name="シャワー")),
                (
                    "roof_rest",
                    models.BooleanField(default=False, verbose_name="屋根付き休憩所"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="住所")),
                ("price", models.TextField(blank=True, verbose_name="料金")),
                ("appeal", models.TextField(blank=True, verbose_name="施設の魅力")),
                ("memo", models.TextField(blank=True, verbose_name="備考")),
                (
                    "official_url",
                    models.URLField(blank=True, verbose_name="公式サイト・SNS"),
                ),
                (
                    "business_hours",
                    models.TextField(blank=True, verbose_name="営業時間"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dogruns/",
                        verbose_name="代表画像",
                    ),
                ),
                (
                    "sub_image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dogruns/",
                        verbose_name="サブ画像1",
                    ),
                ),
                (
                    "sub_image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dogruns/",
                        verbose_name="サブ画像2",
                    ),
                ),
            ],
        ),
    ]
