# Generated by Django 6.0.8 on 2026-09-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogruns", "0005_dogrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogrun",
            name="sub_image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="dogruns/", verbose_name="サブ画像3"
            ),
        ),
    ]
