# Generated by Django 6.0.8 on 2026-09-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogruns", "0006_dogrun_sub_image3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogrun",
            name="parking",
        ),
        migrations.RemoveField(
            model_name="dogrun",
            name="restroom",
        ),
        migrations.RemoveField(
            model_name="dogrun",
            name="roof_rest",
        ),
        migrations.RemoveField(
            model_name="dogrun",
            name="shower",
        ),
        migrations.RemoveField(
            model_name="dogrun",
            name="water",
        ),
        migrations.AddField(
            model_name="dogrun",
            name="agility",
            field=models.BooleanField(default=False, verbose_name="アジリティ"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="bbq",
            field=models.BooleanField(default=False, verbose_name="BBQ"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="cafe",
            field=models.BooleanField(default=False, verbose_name="カフェ併設"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="grass",
            field=models.BooleanField(default=False, verbose_name="天然芝"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="indoor",
            field=models.BooleanField(default=False, verbose_name="屋内"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="large_dog",
            field=models.BooleanField(default=False, verbose_name="大型犬"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="outdoor",
            field=models.BooleanField(default=False, verbose_name="屋外"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="pool",
            field=models.BooleanField(default=False, verbose_name="プール"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="private",
            field=models.BooleanField(default=False, verbose_name="貸切"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="shampoo",
            field=models.BooleanField(default=False, verbose_name="シャンプー施設"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="shop",
            field=models.BooleanField(default=False, verbose_name="ショップ併設"),
        ),
        migrations.AddField(
            model_name="dogrun",
            name="stay",
            field=models.BooleanField(default=False, verbose_name="宿泊施設"),
        ),
        migrations.AlterField(
            model_name="dogrun",
            name="area",
            field=models.CharField(
                choices=[
                    ("seibu", "西部"),
                    ("chubu", "中部"),
                    ("tobu", "東部"),
                    ("izu", "伊豆"),
                ],
                max_length=20,
                verbose_name="エリア",
            ),
        ),
    ]
